[workspace]
members = [
    ".",
    "crates/jiosaavn",
    "crates/shazam-core",
]

[package]
name = "shazam-daemon"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/omsingh02/shazam-daemon"

[lib]
name = "shazam_daemon"
path = "src/lib.rs"

[[bin]]
name = "shazam-daemon"
path = "src/main.rs"

[[bin]]
name = "test_capture"
path = "src/bin/test_capture.rs"

[[bin]]
name = "benchmark"
path = "src/bin/benchmark.rs"

[dependencies]
# Pure DSP, Landmark Fingerprinting & Domain Models (Modular Standalone Crate)
shazam-core = { path = "crates/shazam-core" }

# Audio capture and lock-free buffers
cpal = "0.15"
rtrb = "0.3"

# Binary Serialization & Checksums
byteorder = "1.5"
crc32fast = "1.4"
base64 = "0.22"

# Network & Async
tokio = { version = "1.40", features = ["full", "signal", "process"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.10", features = ["v4"] }
rand = "0.8"
chrono = "0.4"
libc = "0.2"

# D-Bus MPRIS2
zbus = { version = "5.0", features = ["tokio"] }

# CLI arguments & logging
clap = { version = "4.5", features = ["derive"] }

# JioSaavn Decryption & Media Tagging (Modular Standalone Crate)
jiosaavn = { path = "crates/jiosaavn" }
mp4ameta = "0.12"
dirs = "6.0.0"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 12
strip = true
